name: CI

on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Lint
      run: |
        npm install eslint@9.11.1
        npx eslint . \
          --config eslint.config.js